Repository Fimba-Code/discord-bot, pull requests merged in 2020-05, with the labels that each got.

#16 Major refactoring
  package.json
  src/__tests__/greet.test.ts
  src/__tests__/utils/utils.ts
  src/bot/index.ts
  src/config.json
  src/env.ts
  src/functions/greet-new-users.ts
  src/functions/index.ts
  src/functions/messages.ts
  src/functions/user-reactions.ts
  src/helpers/reply-to-users.ts
  src/index.ts
  src/utils/utils.ts
Labels: bot:ranking, enhancement, refactor

#18 Simplified avatar url generation
  src/config.json
  src/functions/messages.ts
  src/helpers/MembersHelper.ts
Labels: enhancement, refactor

#19 :art: Ran prettier
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  src/functions/messages.ts
Labels: enhancement

#23 Message Content
  src/config.json
  src/functions/messages.ts
Labels: enhancement

#24 Fix Code Block Regex
  src/functions/messages.ts
Labels: bot:ranking, enhancement
